### PR TITLE
Update Makefile.PL

### PR DESCRIPTION
**Pull request by toreau**
Include missing Syntax::Keyword::MultiSub.

### CODE REVIEW

**Comment by Ovid** [comment]
`Makefile.PL` is autogenerated from the `dist.ini`, where that module is listed as:

```
[Prereqs / RuntimeSuggests]
Syntax::Keyword::MultiSub = 0.02
Future::AsyncAwait        = 0.58
```

That, in turn, adds those to the `META.json` as:

```
         "suggests" : {
            "Future::AsyncAwait" : "0.58",
            "Syntax::Keyword::MultiSub" : "0.02"
         }
```

And the `cpanfile` as:

```
suggests "Future::AsyncAwait" => "0.58";
suggests "Syntax::Keyword::MultiSub" => "0.02";
```

I'm unsure how that gets added to the `Makefile.PL`.

**Comment by Ovid** [comment]
In other words, your change would be overwritten the next time this is built. If you have suggestions on how to handle that, it would be great.

**Comment by toreau** [comment]
I didn't see dist.ini _or_ the auto-generate comment in Makefile.PL. This is going to be a great weekend. I should probably steer away going for a drive. :)

Apropos poor vision: I _assume_ that `dzil`'s `AutoPrereqs` doesn't see this one:

    load Syntax::Keyword::MultiSub;

**Comment by Ovid** [comment]
For now, closing this.

**Pull request closed without merging**
